SET @Trainer1 :=90002;
-- Clean Trainer before inserting new NPC,spells & skills.
DELETE FROM `creature` WHERE `id`=@Trainer1;
DELETE FROM `creature_template` WHERE `entry`=@Trainer1;
DELETE FROM `npc_trainer` WHERE `entry`=@Trainer1;
-- Create Trainer NPC
INSERT INTO `creature_template` (`entry`,`difficulty_entry_1`,`difficulty_entry_2`,`difficulty_entry_3`,`KillCredit1`,`KillCredit2`,`modelid1`,`modelid2`,`modelid3`,`modelid4`,`name`,`subname`,`IconName`,`gossip_menu_id`,`minlevel`,`maxlevel`,`exp`,`faction_A`,`faction_H`,`npcflag`,`speed_walk`,`speed_run`,`scale`,`rank`,`mindmg`,`maxdmg`,`dmgschool`,`attackpower`,`dmg_multiplier`,`baseattacktime`,`rangeattacktime`,`unit_class`,`unit_flags`,`dynamicflags`,`family`,`trainer_type`,`trainer_spell`,`trainer_class`,`trainer_race`,`minrangedmg`,`maxrangedmg`,`rangedattackpower`,`type`,`type_flags`,`lootid`,`pickpocketloot`,`skinloot`,`resistance1`,`resistance2`,`resistance3`,`resistance4`,`resistance5`,`resistance6`,`spell1`,`spell2`,`spell3`,`spell4`,`spell5`,`spell6`,`spell7`,`spell8`,`PetSpellDataId`,`VehicleId`,`mingold`,`maxgold`,`AIName`,`MovementType`,`InhabitType`,`Health_mod`,`Mana_mod`,`Armor_mod`,`RacialLeader`,`questItem1`,`questItem2`,`questItem3`,`questItem4`,`questItem5`,`questItem6`,`movementId`,`RegenHealth`,`equipment_id`,`mechanic_immune_mask`,`flags_extra`,`ScriptName`,`WDBVerified`) VALUES
(@Trainer1,        -- entry
0,                -- difficulty_entry_1
0,                -- difficulty_entry_2
0,                -- difficulty_entry_3
0,                -- KillCredit1
0,                -- KillCredit2
22931,            -- modelid1
0,                -- modelid2
0,                -- modelid3
0,                -- modelid4
'Stor',   -- name
'Trainer Master', -- subname
'',               -- IconeName
0,                -- gossip_menu_id
80,               -- minlevel
80,               -- maxlevel
0,                -- exp
35,               -- faction_A
35,               -- faction_h
51,               -- npcflag
1,                -- speed_walk
1,                -- speed_run
1,                -- scale
0,                -- rank
1755,             -- mindmg
1755,             -- maxdmg
0,                -- dmgschool
1504,             -- attackpower
1,                -- dmg_multiplier
1500,             -- baseattacktime
0,                -- rangeattacktime
2,                -- unit_class
0,                -- unit_flags
0,                -- dynamicflags
0,                -- family
2,                -- trainer_type
0,                -- trainer_spell
0,                -- trainer_class
0,                -- trainer_race
0,                -- minrangedmg
0,                -- maxrangedmg
0,                -- rangedattackpower
7,                -- type
0,                -- type_flags
0,                -- lootid
0,                -- pickpocketloot
0,                -- skinloot
0,                -- resistance1
0,                -- resistance2
0,                -- resistance3
0,                -- resistance4
0,                -- resistance5
0,                -- resistance6
0,                -- spell1
0,                -- spell2
0,                -- spell3
0,                -- spell4
0,                -- spell5
0,                -- spell6
0,                -- spell7
0,                -- spell8
0,                -- PetSpellDataId
0,                -- VehicleId
0,                -- mingold
0,                -- maxgold
'',               -- AIName
0,                -- MovementType
3,                -- InhabitType
1,                -- Health_mod
1,                -- Mana_mod
1,                -- Armor_mod
0,                -- RacialLeader
0,                -- questItem1
0,                -- questItem2
0,                -- questItem3
0,                -- questItem4
0,                -- questItem5
0,                -- questItem6
0,                -- movementId
1,                -- RegenHealth
0,                -- equipment_id
0,                -- mechanic_immune_mask
0,                -- flags_extra
'',               -- ScriptName
1);               -- WDBVerified

INSERT INTO `npc_trainer` (`entry`,`spell`) VALUES
(@Trainer1,-201001), -- Warrior-Lowlevel
(@Trainer1,-201002), -- Warrior-Highlevel
(@Trainer1,-201003), -- Paladin-Lowlevel
(@Trainer1,-201004), -- Paladin-Highlevel
(@Trainer1,-201005), -- Druid-Lowlevel
(@Trainer1,-201006), -- Druid-Highlevel
(@Trainer1,-201007), -- Mage-Lowlevel
(@Trainer1,-201008), -- Mage-Highlevel
(@Trainer1,-201009), -- Warlock-Lowlevel
(@Trainer1,-201010), -- Warlock-Highlevel
(@Trainer1,-201011), -- Priest-Lowlevel
(@Trainer1,-201012), -- Priest-Highlevel
(@Trainer1,-201013), -- Hunter-Lowlevel
(@Trainer1,-201014), -- Hunter-Highlevel
(@Trainer1,-201015), -- Rogue-Lowlevel
(@Trainer1,-201016), -- Rogue-Highlevel
(@Trainer1,-201017), -- Shaman-Lowlevel
(@Trainer1,-201018), -- Warrior-Lowlevel
(@Trainer1,-201019), -- Warrior-Highlevel
(@Trainer1,-201020), -- Paladin-Lowlevel
(@Trainer1,-201021), -- Paladin-Highlevel
(@Trainer1,-201022), -- Druid-Lowlevel
(@Trainer1,-201023), -- Druid-Highlevel
(@Trainer1,-201024), -- Mage-Lowlevel
(@Trainer1,-201025), -- Mage-Highlevel
(@Trainer1,-201026), -- Warlock-Lowlevel
(@Trainer1,-201027), -- Warlock-Highlevel
(@Trainer1,-201028), -- Priest-Lowlevel
(@Trainer1,-201029), -- Priest-Highlevel
(@Trainer1,-201030), -- Hunter-Lowlevel
(@Trainer1,-201031), -- Hunter-Highlevel
(@Trainer1,-201032), -- Rogue-Lowlevel
(@Trainer1,-201033), -- Rogue-Highlevel
(@Trainer1,-201034), -- Shaman-Lowlevel
(@Trainer1,-201035), -- Hunter-Lowlevel
(@Trainer1,-201036), -- Hunter-Highlevel
(@Trainer1,-201037), -- Rogue-Lowlevel
(@Trainer1,-201038), -- Rogue-Highlevel
(@Trainer1,-201039), -- Shaman-Lowlevel
(@Trainer1,-201040), -- Hunter-Lowlevel
(@Trainer1,-201041), -- Hunter-Highlevel
(@Trainer1,-201042); -- Rogue-Lowlevel