DROP TABLE IF EXISTS `lotto_extractions`;
CREATE TABLE IF NOT EXISTS `lotto_extractions` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `winner` VARCHAR(12) NOT NULL,
  `guid` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `position` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `reward` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `lotto_tickets`;
CREATE TABLE IF NOT EXISTS `lotto_tickets` (
  `id` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `name` VARCHAR(12) NOT NULL,
  `guid` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;